[general]
seedname = "lco_wannier"
jobname = "b10-U3.6"

beta = 10
n_iw = 251
n_tau = 5001
n_iter_dmft = 6

prec_mu = 0.0001
mu_initial_guess = 12.8

h_int_type = "kanamori"
U = 3.6
J = 0.0

dc_type = 0
dc_dmft = false

h5_save_freq = 1

[solver]
type = "cthyb"
length_cycle = 60
n_warmup_cycles = 1e+4
n_cycles_tot = 2e+6
imag_threshold = 1e-6
measure_density_matrix = true
delta_interface=true
perform_tail_fit = true
fit_max_moment = 4
fit_min_w = 6
fit_max_w = 12
